### PR TITLE
Improved performance by about a 20% using InlinedFixedVector in sudoku_specialized.mojo

### PR DESCRIPTION
**Pull request by andresnowak**
Reduced the time from 2.36 seconds to 1.97 in a 3600x

### CODE REVIEW

**Comment by manatlan** [comment]
Thanks @andresnowak !
Can't test now, because not a real computer... (but soon)
But I take !!!

It's the perfect timing ... because I wanted to ask help in mojo communities, to help me to make it as fast as the rust version. (it should be possible ?!)

**Comment by manatlan** [comment]
THanks again @andresnowak 

I've applied your evolution on https://github.com/manatlan/sudoku_resolver/tree/master/optimized (a more advanced algo)
And now : it's as fast as the rust (ultra optimized) version !!!

==> perfect !

the mojo version is a lot simpler/readable than the rust one ... with same speed !
that what I wanted to reach !

**Comment by andresnowak** [comment]
There is also supposedly a problem in mojo where the appending of strings values is slower than in python, but supposedly they are going to fix it in the future. And i would think that the rust version was implemented with auto-vectorization in mind, so yeah for now we could say that both implementation are the same speed

**Comment by manatlan** [comment]
I clearly confirm (when mojo/rust prints to stdout ... mojo is a lot slower .... when both don't prints : it's the same)

**Comment by andresnowak** [comment]
Yeah, it is supposedly something they will fix in the future, but yeah for now it is a small weakness of the language

**Pull request merged**
