### PR TITLE
Remove need to use a HashSet similar to the C version.

### PR DESCRIPTION
**Pull request by sammysheep**
This is closer to the C version, though a bitset might be good to try as well. Hashing over a small dataset requires an allocation; the constant lookup for hashing only matters when the array's size gets large and can be slower (was for my machine: 14 seconds to about 3 seconds).

### CODE REVIEW

**Comment by sammysheep** [comment]
Was faster than the C version on my ancient machine. The output also matched the C version.

**Comment by manatlan** [comment]
Hi

I don't know if I will merge that ...
Ok it uses the same techs as the c. But for C version, there is no hashset ... So no others choice, it makes sense !
If I accept it, I should update all others to profit of the same techs ;-( ... 

The c version is for fun, to have a reference (it was generated by chatgpt). I imagine that a c expert could make it X2 or X4 ... But til now,  it's just tu have a reference.

It will not be the same weapons except if I remove the hashset in all others (for the non specialized versions )
;-(

**Comment by sammysheep** [comment]
Then you might remove the C version and any other versions that don't use a hashset from your benchmark or put them in a different section.

**Comment by manatlan** [comment]
is there an hashset/set type in C/gcc ? do you know ?

The other one, which don't use hashset/set is the mojo version (but the lang is very very young) ... no choice now !

All others uses an hashset/set type

**Comment by sammysheep** [comment]
You would have to write your own or find a library. The point I'm trying to make is that if they are not the same weapons, you should make that clear in your benchmark notes. 

Using an array is clearly faster for this use case similar to changing the data structure for the other data. The reader will not know they differ unless you separate the results or standardize on a method. All languages will have an array type of some kind, but that may be too much work, so separating the results is easier..

**Comment by manatlan** [comment]
ok @sammysheep ...
I understand the trouble ...

I think I will change each simple version, and remove set/type, to use something like the "mojo" version  :

```
fn sqr(g:String,x:Int,y:Int) -> String:
    return g[y*9+x:y*9+x+3] + g[y*9+x+9:y*9+x+12] + g[y*9+x+18:y*9+x+21]
fn col(g:String,x:Int) -> String:
    return g[x::9]
fn row(g:String,y:Int) -> String:
    return g[y*9:y*9+9]
fn free(g:String,x:Int,y:Int) -> String:
    let freeset=col(g,x) + row(g,y) + sqr(g,(x//3)*3,(y//3)*3)
    var ll = String("")
    for i in range(len(ALL)):
        if freeset.find(ALL[i])<0:
            ll += ALL[i]
    return ll
```
which is readable and simple ...

**Comment by manatlan** [comment]
funny ...

I've already made changes in java/js/py (removing the set/type) ... and they are faster ;-)

**Comment by manatlan** [comment]
@sammysheep  @raffimolero @noamtashma ... can u help me ?
Like said before ^^, I've removed all hashset in all languages ... (and everything is a lot faster !!!)

The only exception is rust ;-( ... I can't find the right way to patch it :-( 

In the file https://github.com/manatlan/sudoku_resolver/blob/master/sudoku.rs ... I want to remove free() and freeset(), and replace them with this new free() method (like in java, py, mojo, js ....)

But it won't build the exe ;-(

```rust
fn free(g: &[u8], x: usize, y: usize) -> Vec<u8> {
    let t27 = row(g, y).chain(col(g, x)).chain(sqr(g, x, y));
    let mut freeset = Vec::new();
    for elem in b"123456789" {
        if t27.find(|&c| c == *elem) == None {
            freeset.push(*elem);
        }
    }
    freeset
}

```
any ideas ? 

--> so all algorithm will use the same weapons (string (in rs: byte[])) .... (except C yet)

**Comment by sammysheep** [comment]
This PR patches it for Rust, does it not?

**Comment by sammysheep** [comment]
Ah, I see now, you are trying to refactor into one function. I'll see if I can update the PR then in a bit.

**Comment by sammysheep** [comment]
My two most recent commits will provide two versions you can select from to solve the issue you requested. The first one in [fbe8327](https://github.com/manatlan/sudoku_resolver/pull/11/commits/fbe8327e59f21888deedd5614cdb8826e6308cba) is a more exact replication of what you quoted above. However, iterators get consumed so you have to re-create it each search.

The other commit [ba575d9](https://github.com/manatlan/sudoku_resolver/pull/11/commits/ba575d9a57c5621d3168a0da925d5237e9ba9163) provides a better implementation that is even faster by avoiding allocations and doing a single scan.

**Comment by manatlan** [comment]
thanks @sammysheep !
I've take the https://github.com/manatlan/sudoku_resolver/pull/11/commits/fbe8327e59f21888deedd5614cdb8826e6308cba !
It's exactly what I needed !

the second is a great optim, but "it's not the same weapons as others" ... but I keeped the free_faster() as an example in the code, to see if I can implement the same techs in others too (but need to understand it before ;-))

**Comment by sammysheep** [comment]
@manatlan Cool, glad it helps! 

Yeah, you are right, `free_faster` is technically different because of the bitset + single pass. 

Below is a compromise version (still not as fast as `free_faster`) that uses the same Algorithm but avoids the allocation:
```rust
// Similar to existing implementations using an iterator
fn free(g: &[u8], x: usize, y: usize) -> impl Iterator<Item = u8> + '_ {
    b"123456789".iter().copied().filter(move |elem| {
        // Iterators consume, so this is necessary for correctness
        let mut t27 = row(g, y).chain(col(g, x)).chain(sqr(g, x, y));
        !t27.any(|c| c == *elem)
    })
}
```

**Comment by manatlan** [comment]
Absolutely perfect ... Will use it tonight !

**Comment by manatlan** [comment]
I think I will remove the simplest versions
And just keep the optimized versions
(But need to make a simple rust version of the optimized algo, with byte[])

So the repo will be simpler ...
there will be only the strings version and the specialized ones...
It will be a lot simpler !! 

And after that, I'd like to inject grids in stdin and get results in stdout ...

**Comment by sammysheep** [comment]
Nice, good luck! This was fun.

**Pull request closed without merging**
